### ISSUE TITLE
Ensure security and make music room API public

### ISSUE THREAD

**Issue by dantetemplar** [one-zero-eight/music-room#33]
### Current situation
Music room API available only in docker compose network named `music-room` and all API clients should be inside this network.

### Implementation
- [x] Make sure that all endpoints are verified (have verification fastapi dependency)
- [ ] Remove `music-room` network in [InNoHassle-MusicRoom](https://github.com/one-zero-eight/InNoHassle-MusicRoom) `docker-compose.yaml`
- [ ] Remove `music-room` network in [InNoHassle-Events](https://github.com/one-zero-eight/InNoHassle-Events)  `docker-compose.yaml`

### Related
[docker-compose.yaml:44](https://github.com/one-zero-eight/InNoHassle-MusicRoom/blob/92121da8d2d3f1b5025441edda35f05438d4fe0c/docker-compose.yaml#L44)
```yaml
networks:
  # Create a 'music-room' network for connecting Bot and other services
  music-room:
    driver: bridge
    name: music-room
```

[dependencies.py:48](https://github.com/one-zero-eight/InNoHassle-MusicRoom/blob/92121da8d2d3f1b5025441edda35f05438d4fe0c/src/api/dependencies.py#L48)
```python3
from src.schemas.auth import VerificationResult, VerificationSource  # noqa: E402


class SucceedVerificationResult(VerificationResult):
    success: bool = True
    user_id: int  # not optional
    source: VerificationSource


VerifiedDep: TypeAlias = Annotated[SucceedVerificationResult, Depends(verify_request)]
```

Example of endpoint with verification dependency
```python3
@router.post("/")
async def create_booking(booking: CreateBooking, verified: VerifiedDep) -> ViewBooking | str:
    booking_repository = Dependencies.get(AbstractBookingRepository)
    participant_repository = Dependencies.get(AbstractParticipantRepository)
    user_id = verified.user_id
```

**Comment by dantetemplar** [comment]
I have checked all endpoints, everything should be fine.

@ArtemSBulgakov you can make api public

**Comment by ArtemSBulgakov** [comment]
It is now deployed on https://api.innohassle.ru/music-room/v0/docs
