### ISSUE TITLE
Tell people about the requirement of having username

### ISSUE THREAD

**Issue by ArtemSBulgakov** [one-zero-eight/music-room#42]
### Describe the feature

Currently users see error that doesn't say anything about username requirement.

### Suggested solution

While filling the profile, users without username should see the message with requirement of setting username in Telegram settings. Perhaps, they should see it even if they clear username later.

**Comment by dantetemplar** [comment]
Or rework bot so that it will be work fine without usernames. Mentions can be implemented by user id (`[inline mention of a user](tg://user?id=123456789)`). Need to check stuff with "username" and "alias"
